version: "3.8"
services:
  front:
    container_name: front
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - /front/node_modules
      - ./front:/front
    ports:
      - "3002:3002"
    depends_on:
      - design_system

  design_system:
    container_name: DesignSystem
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./DesignSystem
    volumes:
      - /DesignSystem/node_modules
      - ./DesignSystem:/DesignSystem
    ports:
      - "6006:6006"
